[package]
name = "day02"
version = "0.1.0"
edition = "2021"

[dependencies]
input = { path = "../input" }
itertools = "0.13.0"
nom = "7.1.3"
nom-supreme = "0.8.0"

[dev-dependencies]
divan = "0.1.4"

[[bench]]
name = "day02-bench"
path = "benches/benchmarks.rs"
harness = false
